[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:start-desktop]
command=/usr/local/bin/start-desktop.sh
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:websockify]
command=/usr/bin/websockify --web=/usr/share/novnc/ --cert=/root/self.pem 6080 localhost:5901
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
